<?php
$typeArr[1] = '帮助中心';
$typeArr[2] = '旅游线路';
$typeArr[6] = '周边旅游';
$typeArr[5] = '港澳台';
$typeArr[7] = '新手入门';
$typeArr[8] = '客户服务';
$typeArr[9] = '预订须知';
$typeArr[10] = '出行相关';
$typeArr[11] = '途风合作';
$typeArr[12] = '关于我们';
$typeArr[13] = '广告管理';
$typeArr[14] = 'banner管理';
$typeArr[16] = '资讯动态';
$typeArr[17] = '旅游指南';
$typeArr[18] = '旅游指南';
$typeArr[19] = '国内线路';
$typeArr[20] = '出境线路';
$typeArr[21] = '旅游攻略';
$typeArr[31] = '首页主页广告';
$typeArr[32] = '左侧视频';
$typeArr[28] = '网站使用流程';
$typeArr[29] = '发票 合同 退款';
$typeArr[30] = '会员积分相关';
?>